version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123mudar
      MYSQL_DATABASE: phonebook
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
  api_phonebook:
    image: api_phonebook
    container_name: api_phonebook
    ports:
      - "3333:3333"
    expose:
      - "3333"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
