version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123mudar
      MYSQL_DATABASE: phonebook
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
